### PR TITLE
generate function declarations and definitions for contained FBlock containers

### LINKED ISSUE #3: handle FunctionBlockContainer containing FunctionBlockContainer
pending tasks:
* generate function declarations in header file
* create a separate template for `FunctionBlockContainer`, to be called from the root templates.

### LINKED ISSUE #13: Generated header file does not include function prototype
When working on the component behavior language, I wanted to call the C function generated from the schedule in an example algorithm model (the outer function block is called `update` and the schedule is called `schedule`), but the generated header file, `update.h`, does not include a function prototype:

```c
#ifndef UPDATE_H
#define UPDATE_H

/* define structs */

#endif
```

I think this file should contain a function prototype like

```c
void update_schedule(int const *in, int *out);
```

### PR DESCRIPTION
**Pull request by minhnh**
* generate definitions for schedules of `FunctionBlockContainer`'s contained in a root `FunctionBlockContainer`
* generate declarations for  schedules of the root `FunctionBlockContainer`, schedules of contained `FunctionBlockContainer`'s, and contained `FunctionBlock`'s
* make templates for `EmptyFunctionBlock` inline to reduce cluttering
* should resolve #13 
* should resolve #3

### CODE REVIEW

**Review by scymtym — CHANGES_REQUESTED** [review]
* The generated function declarations now allow the OROCOS component to build without modifying the generated code.
* I noticed that declarations and definitions are generated for `EmptyFunctionBlock` instances. I thought `EmptyFunctionBlock` represented pre-defined functions so I expected just a declaration and no definition for those.
* I think the generated C functions for inner function blocks should use "fully qualified" names, i.e. taking into account the names of ancestor function blocks to avoid symbol collisions. For example code generated for a function block "foo" containing a function block "bar" and a function block "baz" containing a function block "bar" would result in two C functions named "bar" with the current naming scheme.

**Comment by minhnh** [comment]
I'm not sure what's the intention for `EmptyFunctionBlock` is actually, maybe @svenschneider can clarify this here. I'm ok with ignoring it when generating function definitions.

I think handling naming of functions should be in a separate issue, since I think it's not critical at the moment. An additional, related issue is that I'm not sure what's the best way to ensure function call, function declaration and function definitions all use the same name in a more scalable manner (as opposed to manually specifying the names in each template).

**Review by scymtym — APPROVED** [review]

**Comment by scymtym** [comment]
I'm fine with postponing the issues I raised since these changes allow the OROCOS component generator to work which would be nice for tomorrow's mvp report.

**Comment by scymtym** [comment]
> I think handling naming of functions should be in a separate issue, since I think it's not critical at the moment. An additional, related issue is that I'm not sure what's the best way to ensure function call, function declaration and function definitions all use the same name in a more scalable manner (as opposed to manually specifying the names in each template).

Having this and exposing it would also benefit the component generator since it has to emit calls to the generated functions.

**Pull request merged**
